apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-erhv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-erhv
    app.kubernetes.io/part-of: tkwch-fix-0075-0008-app
  name: devfile-sample-erhv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-erhv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-erhv
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0008-tenant/tkwch-fix-0075-0008-app/devfile-sample-erhv@sha256:23759c182fd343d52f83fa23a378f17632f05118757c575c2650856be2144f75
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
